### PR TITLE
Update Microsoft Bot Framework scope to v3.1

### PR DESCRIPTION
**Pull request by khaledelmahdi**
Update OAuth scope from `https://graph.microsoft.com/.default` to `https://api.botframework.com/.default`

### CODE REVIEW

**Comment by khaledelmahdi** [comment]
Update Microsoft Bot Framework scope to v3.1

**Comment by mpociot** [comment]
What are the advantages of using this scope?
Can you tell me, where in the documentation this scope is referenced?

Thank you :)

**Comment by khaledelmahdi** [comment]
Hi,

These chages to reflect the latest documentation here: [Authentication calls from the bot to the Bot Connector service](https://docs.botframework.com/en-us/restapi/authentication/#changes)

Thank you.

**Comment by khaledelmahdi** [comment]
The changes I made actually change the POST url and the scope URL.

**Comment by mpociot** [comment]
Great. Thank you :)

**Pull request merged**
