### PR TITLE
Add extras parameter action Incomplete ApiAi

### PR DESCRIPTION
**Pull request by iboldurev**

### CODE REVIEW

**Comment by mpociot** [comment]
Thanks for the PR. Will this fix #282?

**Comment by iboldurev** [comment]
@mpociot Hi, yes it solves my question to some extent. Can you create a new release version with this change?

**Comment by iboldurev** [comment]
@mpociot I found a bug, now I'm fixing it

**Comment by iboldurev** [comment]
@mpociot I'm fixing it, and create pr

**Pull request merged**
