### PR TITLE
fix botframework not using shorthand closing tags

### PR DESCRIPTION
**Pull request by thedotedge**
Please see https://github.com/mpociot/botman/issues/344. Botframework conversations seems to be broken now.

### CODE REVIEW

**Comment by mpociot** [comment]
Please create a new PR / change the PR destination to the 1.5 branch, since this is a bugfix for the 1.5.x version. 

Thank you!

**Comment by thedotedge** [comment]
Sure, done.

**Comment by thedotedge** [comment]
Thanks @mpociot, will you cut a new patch soon?
P.S. Just a thought: maybe it makes sense to call release branches like `1.6.x`?

**Comment by mpociot** [comment]
Yes, I'll Tag a new release in a few minutes. 
The 1.5 branch is the current stable version branch and the master is always for the next unreleased version. Because I thought that it becomes 1.6, but with the changes and new features that I plan, it's becoming 2.0 :)

**Pull request merged**
