### PR TITLE
Allow to reply with a file (Slack RTM only)

### PR DESCRIPTION
**Pull request by baopham**
This needs mpociot/slack-client#2

### CODE REVIEW

**Comment by mpociot** [comment]
First of all - thank you for the PR! Great job.
I think it would be better if we could manage to send a File **and** a normal textual message at the same time. This is not possible right now.

So sending a message like this will only send a file, but the text will be lost.

```php
$bot->say(Message::create('check out this file')->filePath($myFile));
```

**Comment by baopham** [comment]
Ah, yeah, I set the message text as "title":

```
 + $fileToUpload = (new File())
 +                    ->setTitle($message->getMessage())
 +                    ->setPath($message->getFilePath());
```

And then it will look like this:

image

What do you think? Or maybe: we could use the file's name as title which is the default when you upload something to slack manually and set the message text as comments. This sound like a better alternative?

**Comment by mpociot** [comment]
Yeah, adding the message text as a comment might be the better way. Can you please change the PR?

**Comment by baopham** [comment]
Yep, will do.

**Comment by baopham** [comment]
2 issues from Scrutinizer. Fixing...

**Comment by baopham** [comment]
This issue from Scrutinizer `The method fileUpload() does not seem to exist on object<Slack\RealTimeClient>` is probably because it doesn't get the latest `slack-client` code or it doesn't know that `fileUpload()` would come from the parent class `ApiClient` ¯\_(ツ)_/¯

Anyway, I have updated to post the message as the file's comment 😃

**Comment by mpociot** [comment]
Great! Thank you

**Pull request merged**
