### PR TITLE
use statement missed in Conversation.php

### PR DESCRIPTION
**Pull request by sasha-x**

### CODE REVIEW

**Comment by feralheart** [comment]
Hi @sasha-x ,
Thank you for your contribution, but this issue was already resolved in #1105

**Comment by sasha-x** [comment]
May be. What about other PRs?

**Comment by feralheart** [comment]
They're under review at the moment.Is there any PR what you advise to check with higher priority?

**Comment by sasha-x** [comment]
Not sure. It all are 6+ month old.
When I work hard with botman I make my own fork of several repos I need to fix/improve quickly. 
Some of it published here: https://github.com/botman-fork
May be some of these code will be useful.

**Comment by feralheart** [comment]
Thank you for showing your work.
Can you make PRs about your changes?

**Comment by sasha-x** [comment]
Yes, I'll try.

**Comment by feralheart** [comment]
Thank you

**Pull request closed without merging**
