### PR TITLE
Fix ApiAi Middleware

### PR DESCRIPTION
**Pull request by iboldurev**

### CODE REVIEW

**Comment by mpociot** [comment]
Why do we need the version parameter?

**Comment by iboldurev** [comment]
The mandatory version must be submitted in the request, according to the documentation
Also, if you do not send the version in the request, you do not send the data about the completion of the action

**Comment by iboldurev** [comment]
https://docs.api.ai/docs/query#post-query

**Comment by iboldurev** [comment]
@mpociot If we briefly explain, then without passing a version parameter, the action Incomplete parameter is not passed in response to the query

**Comment by iboldurev** [comment]
@mpociot You can take pr?

**Pull request merged**
