### PR TITLE
Feature/add url property on button

### PR DESCRIPTION
**Pull request by sulfanoaf**
* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug Fix

* **What is the current behavior?** (You can also link to an open issue here)

cannot use button when create question

* **What is the new behavior (if this is a feature change)?**

button work properly

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No, users just have to re run composer-install

* **Other information**:

### CODE REVIEW

**Comment by feralheart** [comment]
Thank you for your contribution

**Comment by chimit** [comment]
@sulfanoaf how to use this feature? If I set an URL without setting value on a Button Telegram just doesn't respond:

```php
Button::create('Go there')->url('https://google.com'),
```

If I set a value the button works like usual button (no URL behaviour):

```php
Button::create('Go there')->url('https://google.com')->value('go'),
```

**Comment by Londeren** [comment]
You can use ` Button::create('Go there')->additionalParameters(['url' => 'https://google.com'])`

**Comment by chimit** [comment]
@Londeren of course, I can but we are talking about this PR.

**Pull request merged**
