### PR TITLE
Structured Attachments

### PR DESCRIPTION
**Pull request by SergiX44**
This allows you to maintain information on the single attachment payload, without having to access the full payload of the message. In some cases this does not add significant information (like Facebook or WeChat) while others (like BotFramework or Telegram) keeps information such as the id of the file and the content type of the single attachment. This also allows to maintain a complete abstraction of the type of attachment received.

### CODE REVIEW

**Comment by mpociot** [comment]
I like this change. I'm just not sure on when to include it, as it will introduce a breaking change - which would result in a 2.x release.

**Comment by SergiX44** [comment]
Currently is not ready yet, now it works for receiving, attachment objects are delivered to the closure correctly, but i want make it also for replying and sending.
I do not think that this is a change so big, i think that this can be added in 1.6.x when finished.

**Comment by SergiX44** [comment]
@mpociot I think that now it's ready, tell me if I'm forgetting something.

**Comment by mpociot** [comment]
Great - give me some time to review your changes.

**Comment by SergiX44** [comment]
@mpociot fixed for the latest middleware major update

**Comment by mpociot** [comment]
As this PR was quite large, it took some time to review it.
It's now merged into master and will find it's way into the 2.0 release 🎉  

Thank you very much!

I changed the Message class to typehint Attachments in the `withAttachment` method. Other than that it looked good! 👍

**Pull request merged**
