### PR TITLE
Feature - add we chat listener

### PR DESCRIPTION
**Pull request by christophrumpel**
I added the WeChat drivers for audio, video and location.

### CODE REVIEW

**Comment by christophrumpel** [comment]
Hmm I am not sure why there are so many old commits in there, should be just the last three.

**Comment by christophrumpel** [comment]
Styles and one test fixed, but not sure about the last failing test. I don't see the connection between `LaravelTest the_facade_works` method and the `Curl post method`?

```
9) Mpociot\BotMan\Tests\LaravelTest::the_facade_works
Mockery\Exception\InvalidCountException: Method post('https://api.wechat.com/cgi-bin/token?grant_type=client_credential&appid=WECHAT-APP-ID&secret=WECHAT-APP-KEY', [], []) from Mockery_13_Mpociot_BotMan_Http_Curl should be called
 exactly 1 times but called 2 times.
```

**Comment by mpociot** [comment]
@christophrumpel Yeah, the error is a bit misleading.

The problem is actually, that you do not close the mockery calls. This results in this strange behavior because the assertions how many times a mocked method gets called is now done in another test - because this test has the teardown / mockery close call.

I applied the relevant fixes in this commit: https://github.com/mpociot/botman/commit/a9cdb740adc1ac26ddb3441b4c8588f1822222b9

**Comment by christophrumpel** [comment]
ah I see. thx a lot!

**Pull request merged**
