### PR TITLE
Added support for X-HUB-SIGNATURE header (#79)

### PR DESCRIPTION
**Pull request by ribb3r**

### CODE REVIEW

**Comment by mpociot** [comment]
Thank you for the pull request. Can you also add a test to the Facebook driver that sends a header and matches the request?

I'll also add a note to the readme that the Facebook secret is optional!

**Comment by ribb3r** [comment]
I just adjusted the unit test.

**Comment by mpociot** [comment]
Thank you, can you also tell me if the `facebook_app_secret` is the one that also gets used when verifying the webhook the first time?
Then we could adjust the verification steps too and use the config value as a default: https://github.com/mpociot/botman/blob/master/src/Mpociot/BotMan/Traits/VerifiesServices.php#L29

**Comment by ribb3r** [comment]
I think the X-HUB-SIGNATURE header key/value will not be set during webhook verification. Only during message post requests.

**Comment by mpociot** [comment]
No, I wanted to know if the `hub_verify_token` Facebook sends when you add the webhook for the first time, is the same as the `facebook_app_secret` you use for the hub signature header key.

**Comment by ribb3r** [comment]
ok, I see: `hub_verify_token` != `facebook_app_secret`

The `facebook_app_secret` will be generated if you add a new Facebook app. [See](https://i.stack.imgur.com/8jfDy.png)

I hope I understood you correctly :-)

**Comment by mpociot** [comment]
Yeah that's what I meant. The code looks good - I'll update the readme / facebook documentation to state how to obtain the secret and what it's used for and merge it 👍

**Pull request merged**
