### PR TITLE
Hear Facebook audio, attachment and location messages

### PR DESCRIPTION
**Pull request by christophrumpel**
Add FacebookAudioDriver to listen for Facebook audio files

### CODE REVIEW

**Comment by christophrumpel** [comment]
@mpociot the `FacebookImageDriver` you did first didn't had any tests. My new driver does not have them either. Let me know if you need them and if yes how they could work.

**Comment by mpociot** [comment]
Oh you're right. Do you want to add the tests?

**Comment by christophrumpel** [comment]
Yeah I can do that. How would you test `matchesRequest` and `getMessages` since they depend on `$this->event` or `$this->config->has`. Could you do one for to see how they could look like? If you don't have time I can of course try it myself.

**Comment by kmarima** [comment]
question .... how would i use this ?

**Comment by christophrumpel** [comment]
@kmarima it is not finished yet. Right now in this branch it works like this:

```php
// Attachments
        $botman->receivesAttachment(function(BotMan $bot) {
            $data = $bot->getAttachment();
            $bot->reply('attachment received: ' . $data[0]);
        });
```

But we are still talking about implementing it a little bit different. There will be documentation when It is finished.

**Comment by christophrumpel** [comment]
So, just rebuild it to load the attachments from the message and not from the botman object. Also added tests. If you see anything you want changes, just name it @mpociot 

I will add the FB video driver as well today.

**Comment by christophrumpel** [comment]
Added the Facebook Video driver too.

**Comment by mpociot** [comment]
Great work! Thank you!

**Pull request merged**
