### PR TITLE
[Feature] add apiai middleware

### PR DESCRIPTION
**Pull request by christophrumpel**
This adds an API.ai middleware to the framework, so you can make use of the API.ai platform.

This is how you can use it. It works like the given Wit.ai platform.

```php
    // create a botman instance
    $botman = app('botman');

    // add the middleware
    $botman->middleware(ApiAi::create('your-api-ai-token'));

    // give the bot something to listen for
    $botman->hears('.*', function ($bot) {
        $extras = $bot->getMessage()->getExtras();
        $bot->reply(implode(' ,' , $extras));
    });

    // start listening
    $botman->listen();
```

### CODE REVIEW

**Comment by mpociot** [comment]
Thank you for the pull request. I think API.ai is a highly requested addition to BotMan. 

Your tests fail because the middleware class name is ApiAi while the file name is Apiai. Could you please fix the case sensitive errors and apply the style fixes to your pr?

**Comment by christophrumpel** [comment]
Thx. Interesting why my tests succeeded... but of course I'll fix it as well as the styles.

**Comment by christophrumpel** [comment]
I am not sure what the remaining styl error means? Delete the curly brace and add it again? Don't get it.

And it fails with php 5.6 because I am using the null coalescing operator. I can change that to `isset()` ok?

**Comment by mpociot** [comment]
Yes, please use isset. I also thought about dropping 5.6 support, but I think I don't want to right now. 

The brace maybe has a wrong indentation (tabs)?

**Pull request merged**
