### PR TITLE
Add Telegram Video and Audio driver

### PR DESCRIPTION
**Pull request by christophrumpel**
Adding the Telegram Video Driver with test.

### CODE REVIEW

**Comment by christophrumpel** [comment]
I am finished with the Telegram drivers. Two things I want to mention:

1.) I am not sure if `->receivesAttachments` is the right naming choice here since an image or audio or video would be an attachment too, when you think about it.

2.) With Telegram there are to specific file types like with Facebook, they are all a `document` and there is additionally the `mime_type` for more details. So for audio, video and image I just checked the first part of the mime_type, everything else that is a `document` you will get receive with `receivesAttachment`. (e.g. text file, zip file etc.)

**Comment by mpociot** [comment]
I thought that receivesAttachment would trigger in these cases too! So if you want to listen for any kind of files, use this method. 

This would mean that it should retrieve images and videos too - do. we have any problem with this on Facebook?

**Comment by christophrumpel** [comment]
Ah ok I did not get that, yeah makes more sense. Not that's totally fine with Facebook. I just need to change it there too. But first I wann change it for Telegram here.

**Comment by christophrumpel** [comment]
@mpociot It seems this is not working this way because when we implement it like this (AttachmentDriver listens to all attachments), then we have multiple drivers that could be valid for the request. E.g. an image would fit in the TelegramPhotoDriver and in the TelegramAttachmentDriver and only the first one listed in the `DriverManger` will get triggered.

Not sure what would be the best solution to handle that. Do you have an idea?

**Comment by mpociot** [comment]
Maybe we can just make the `receivesAttachment` method listen for all of the "attachment" (video/audio/image) patterns combined?

**Comment by christophrumpel** [comment]
So like we discussed I know removed the Telegram attachment driver and `receivesAttachment` method, since there is no good way right now this could work. We want to focus on `image`, `audio` and `video` right now.

**Pull request merged**
