### PR TITLE
Added video send method for facebook

### PR DESCRIPTION
**Pull request by ngfw**

### CODE REVIEW

**Comment by christophrumpel** [comment]
@ngfw you need one style fix to the checks pass.

**Comment by mpociot** [comment]
Thanks for the PR. I like the video feature. I will add support for all other possible drivers and merge this pr when I'm done

**Comment by mpociot** [comment]
I added support for video messages in Telegram, Facebook and the MS BotFramework driver.
See https://github.com/mpociot/botman/commit/4bf84fd831bef8bce3206d63b96b2fb39fc6ebfa

**Comment by ngfw** [comment]
Thanks!

**Pull request closed without merging**
